FROM --platform=$BUILDPLATFORM golang:alpine as builder

ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . ./

RUN CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=linux go build -a -o shortu .

# stage 2

FROM alpine:latest

WORKDIR /root

COPY --from=builder /app/main .

EXPOSE 3000

CMD ./feed